#!/usr/bin/env bash

set -x
# mvn clean dependency:purge-local-repository;
mvn -DskipTests --projects CIMConnector,GridLAB-D,ShortCircuit,Simulation,Spatial,CIMWeb,CIMEar install; docker build --quiet --tag derrickoswald/cimapplication .
