#!/usr/bin/env bash

set -x
# mvn clean dependency:purge-local-repository;
mvn clean -Dmaven.test.skip=true -DskipTests -DskipITs --projects CIMConnector,Ingest,TimeSeries,GridLAB-D,ShortCircuit,MaximumFeedIn,Simulation,Spatial,CIMWeb,CIMEar install; docker build --quiet --tag derrickoswald/cimapplication .
