#!/usr/bin/env bash

if [[ $# -eq 0 ]] ; then
    master=localhost
else
    master=$1
fi

docker run --name tomee --rm --network spark_default --env HDFS_USER=${USER} --env HADOOP_USER_NAME=${USER} --publish 9080:8080 --publish 5040:4040 --publish 51070:50070 --volume /home/derrick/code/CIMReader/private_data:/opt/private_data derrickoswald/cimapplication start-tomee $master
