#!/usr/bin/env bash

if [[ $1 == wildfly ]]; then
    AppServer="Wildfly"
    Tag="wildfly"
    shift
elif [[ $1 == tomee ]]; then
    AppServer="TomEE"
    Tag="tomee"
    shift
elif [[ $1 == glassfish ]]; then
    AppServer="Glassfish"
    Tag="glassfish"
    shift
elif [[ $1 == openliberty ]]; then
    AppServer="OpenLiberty"
    Tag="openliberty"
    shift
else
    AppServer="TomEE"
    Tag="tomee"
fi

set -x
# mvn clean dependency:purge-local-repository;
mvn clean -Dmaven.test.skip=true -DskipTests -DskipITs --projects CIMConnector,CIMWeb,CIMEar install
STATUS=$?
if [ $STATUS -eq 0 ]; then
docker build --quiet --file ${AppServer}.Dockerfile --tag derrickoswald/cimapplication:${Tag} .;docker tag derrickoswald/cimapplication:${Tag} derrickoswald/cimapplication:latest
else
echo "Maven failed"
fi
